<?php

declare(strict_types=1);

namespace NEOSidekick\AiAssistant\Command;

use Neos\Flow\Annotations as Flow;
use Neos\Flow\Cli\CommandController;
use NEOSidekick\AiAssistant\Dto\AgentSigningKeyPushResult;
use NEOSidekick\AiAssistant\Service\AgentKeyPairService;
use NEOSidekick\AiAssistant\Service\AgentSigningKeyPushService;
use RuntimeException;

/**
 * CLI commands around the RSA keypair that signs new-generation agent JWTs
 * (see AgentKeyPairService).
 *
 * The keypair is stored in the database (one row per installation) and is otherwise
 * generated by the first editor authorization, which pushes it to NEOSidekick right
 * away; these commands provision it explicitly or read the fingerprint that identifies
 * this installation. The NEOSidekick backend module regenerates the key through the
 * same path (AgentSigningKeyPushService::rotateKeyPair()).
 *
 * @Flow\Scope("singleton")
 */
class AgentKeyCommandController extends CommandController
{
    /**
     * @Flow\Inject
     * @var AgentKeyPairService
     */
    protected $agentKeyPairService;

    /**
     * @Flow\Inject
     * @var AgentSigningKeyPushService
     */
    protected $agentSigningKeyPushService;

    /**
     * Generate the RSA keypair used to sign agent JWTs
     *
     * Generates an RSA 2048 keypair, stores it in the database and prints its key id
     * and fingerprint. Fails if a keypair already exists unless --force is given.
     *
     * With --force the new key is created as a PENDING pair next to the current one
     * and transmitted to NEOSidekick chained to the current key - that proof of
     * possession keeps the installation's identity. Only NEOSidekick's confirmation
     * makes the new key the live one; until then the current key stays in use and
     * everyone stays connected. If the confirmation does not arrive, re-run the
     * command: the SAME pending key is transmitted again. Exits with 1 whenever
     * NEOSidekick did not confirm the key.
     *
     * A regeneration never re-enrols this installation on its own: if the stored keypair
     * cannot vouch for the successor, the command aborts, because an unchained push would
     * start a new lineage and every connected tool would have to be reconnected. Restore the
     * signing-key row from a backup to keep them, or re-enrol explicitly with the checkbox
     * on the regeneration form in the NEOSidekick module. As a shell-only fallback, DELETE
     * FROM neosidekick_aiassistant_domain_model_agentsigningkeyrecord followed by
     * ./flow agentkey:generate does the same thing.
     *
     * With --relabel (only together with --force) NEOSidekick registers the new key
     * under this site's current domain instead of the domain the current key is
     * registered for - for a site that moved. The flag sticks to the pending key
     * until it is confirmed. Never run --relabel on a copy of another installation's
     * database (a staging site restored from a production dump): the copy shares the
     * production identity, and relabelling it revokes production's live key. Give a copy
     * its own identity instead - tick the re-enrolment checkbox on the regeneration form
     * in the NEOSidekick module and press "Regenerate key".
     *
     * @param bool $force Replace an existing keypair
     * @param string|null $domain The domain to register the key under, e.g. https://www.example.com.
     *                            Required unless Neos.Flow.http.baseUri is configured: on the shell
     *                            there is no request to take it from, and it must never be guessed.
     * @param bool $relabel Re-register the installation under the pushed domain (requires --force)
     */
    public function generateCommand(bool $force = false, ?string $domain = null, bool $relabel = false): void
    {
        $this->outputPendingRegenerationNotice();

        if ($relabel && !$force) {
            $this->outputLine('<error>--relabel only applies to a regeneration: re-run with --force --relabel.</error>');
            $this->quit(1);
        }

        $hadLivePair = $this->agentKeyPairService->hasKeyPair();
        if ($hadLivePair && !$force) {
            $this->outputLine('<error>An agent signing keypair already exists.</error>');
            $this->outputLine('Re-run with <b>--force</b> to replace it. The new key is transmitted to NEOSidekick chained to the current one and takes over only once NEOSidekick confirmed it.');
            $this->quit(1);
        }

        if ($hadLivePair && !$this->agentKeyPairService->isLiveKeyPairUsable()) {
            $this->outputLine('<error>The key was not regenerated: %s</error>', [AgentSigningKeyPushService::UNUSABLE_KEYPAIR_ABORT_MESSAGE]);
            $this->outputAbortedReenrolmentPaths();
            $this->quit(1);
        }

        $hadPendingPair = $this->agentKeyPairService->hasPendingKeyPair();
        $result = $this->agentSigningKeyPushService->rotateKeyPair($domain, $relabel);
        if (!$result->successful) {
            if ($this->agentKeyPairService->hasPendingKeyPair()) {
                $this->outputLine('<comment>The new key was not confirmed by NEOSidekick: %s</comment>', [(string)$result->errorMessage]);
                $this->outputLine('Nothing has changed: this installation keeps using its current key and everyone stays connected. The new key is kept as a pending pair;');
                $this->outputLine('re-run <b>./flow agentkey:generate --force</b> to transmit the SAME pending key - no third key is created.');
            } elseif (!$hadLivePair && $this->agentKeyPairService->hasKeyPair()) {
                $this->outputLine('<success>Generated a new RSA %d agent signing keypair.</success>', [2048]);
                $this->outputKeyDetails();
                $this->outputLine();
                $this->outputLine('<comment>The public key could not be pushed to NEOSidekick: %s</comment>', [(string)$result->errorMessage]);
                $this->outputLine('Retry with <b>./flow agentkey:push</b>; the authorization flow retries it as well.');
            } else {
                $this->outputLine('<error>The key was not regenerated: %s</error>', [(string)$result->errorMessage]);
            }
            $this->outputModuleHint();
            $this->quit(1);
        }

        if ($hadPendingPair) {
            $transmittedLine = 'Transmitted the pending key; it is the live agent signing key now.';
            $this->outputLine($result->isConfirmed() ? '<success>' . $transmittedLine . '</success>' : $transmittedLine);
        } else {
            $this->outputLine('<success>Generated a new RSA %d agent signing keypair.</success>', [2048]);
        }
        $this->outputKeyDetails();
        $this->outputLine();
        $this->outputPushResult($result);
        $this->outputModuleHint();

        if (!$result->isConfirmed()) {
            $this->quit(1);
        }
    }

    /**
     * Push the public agent signing key to NEOSidekick
     *
     * Sends the public key, its key id, this installation's address and its signed host set
     * (the active Neos domain records and the base URI) to NEOSidekick over the same
     * authenticated channel as the authorization callback, and prints the status
     * NEOSidekick recorded for it. The authorization flow pushes the key automatically
     * the first time an editor authorizes; this command is for provisioning it before
     * that happens. While a regeneration is unconfirmed, the pending key is transmitted
     * with the regeneration's longer timeout.
     *
     * @param string|null $domain The domain to register the key under, e.g. https://www.example.com.
     *                            Required unless Neos.Flow.http.baseUri is configured: on the shell
     *                            there is no request to take it from, and the domain becomes the key's
     *                            label in NEOSidekick, which decides where token renewals may be sent,
     *                            so it must never be guessed.
     */
    public function pushCommand(?string $domain = null): void
    {
        $this->outputPendingRegenerationNotice();

        if (!$this->agentKeyPairService->hasKeyPair()) {
            $this->outputLine('<comment>No agent signing keypair exists yet.</comment>');
            $this->outputLine('Run <b>./flow agentkey:generate</b> to create one - it is pushed to NEOSidekick right away.');
            $this->quit(1);
        }

        $result = $this->agentSigningKeyPushService->push(null, null, $domain);
        if (!$result->successful) {
            $this->outputLine('<error>%s</error>', [(string)$result->errorMessage]);
            $this->quit(1);
        }

        $this->outputPushResult($result);
    }

    /**
     * Show the key id and fingerprint of the agent signing keypair
     *
     * Prints the key id (JWT `kid` header value), the display fingerprint identifying
     * this installation's key, and the PEM-encoded public key. Does not generate a
     * keypair if none exists.
     */
    public function showCommand(): void
    {
        if (!$this->agentKeyPairService->hasKeyPair()) {
            $this->outputLine('<comment>No agent signing keypair exists yet.</comment>');
            $this->outputLine('Run <b>./flow agentkey:generate</b> to create one (the first editor authorization creates and pushes it as well).');
            $this->quit(1);
        }

        $this->outputKeyDetails();
        $this->outputLine();
        $this->outputLine('%s', [$this->agentKeyPairService->getPublicKeyPem()]);
    }

    /**
     * A stored pair the keypair service refuses to serve (a hand-edited row, a partial restore)
     * cannot be regenerated: a successor it cannot sign for would enrol this installation anew.
     *
     * @return array{0: string, 1: string} The key id and the fingerprint
     */
    private function readKeyDetailsOrQuit(): array
    {
        try {
            return [$this->agentKeyPairService->getKeyId(), $this->agentKeyPairService->getFingerprint()];
        } catch (RuntimeException $exception) {
            $this->outputLine('<error>The stored agent signing keypair is unusable.</error>');
            $this->outputLine('%s', [$exception->getMessage()]);
            $this->outputLine('Restore the signing-key row from a backup to keep this installation\'s identity - a regeneration cannot chain to an unusable key and is refused.');
            $this->outputAbortedReenrolmentPaths();
        }
        $this->quit(1);

        return ['', ''];
    }

    /**
     * Re-enrolment orphans every connected tool, so it is never a side effect of a regeneration:
     * it is asked for on one of these two paths.
     */
    private function outputAbortedReenrolmentPaths(): void
    {
        $this->outputLine('To enrol this installation as a NEW one - every connected tool must then be reconnected - tick the re-enrolment checkbox on the regeneration form in the NEOSidekick module > Configuration and press "Regenerate key".');
        $this->outputLine('As a shell-only fallback, <b>DELETE FROM neosidekick_aiassistant_domain_model_agentsigningkeyrecord</b> followed by <b>./flow agentkey:generate</b> does the same thing.');
    }

    /**
     * The pending pair is the key NEOSidekick may already have accepted, so the operator must
     * not be surprised that the next push transmits it instead of the live key.
     */
    private function outputPendingRegenerationNotice(): void
    {
        if (!$this->agentKeyPairService->hasPendingKeyPair()) {
            return;
        }

        $this->outputLine('<comment>A regeneration of this installation\'s key is incomplete: the new key exists locally but was never confirmed by NEOSidekick. Re-run <b>./flow agentkey:generate --force</b> to transmit the SAME pending key - it is the key NEOSidekick may already have accepted.</comment>');
    }

    private function outputModuleHint(): void
    {
        $this->outputLine('Administrators can also regenerate the key in the Neos backend: NEOSidekick module > Configuration > "Regenerate key".');
    }

    /**
     * Shared by both commands. A readable 200 always means NEOSidekick registered the key, so
     * pushing it again cannot change a status other than "confirmed" - a regeneration can, because
     * it chains a fresh key and re-enrolls this installation.
     */
    private function outputPushResult(AgentSigningKeyPushResult $result): void
    {
        if ($result->isConfirmed()) {
            $this->outputLine('<success>Pushed the public key to NEOSidekick.</success>');
        } else {
            $this->outputLine('<comment>Pushed the public key to NEOSidekick, but NEOSidekick did not confirm it.</comment>');
        }
        $this->outputLine('Status:        %s', [(string)$result->status]);
        if ($result->fingerprint !== null) {
            $this->outputLine('Fingerprint:   %s', [$result->fingerprint]);
        }
        if ($result->installRootKid !== null) {
            $this->outputLine('Installation:  %s', [$result->installRootKid]);
        }

        if ($result->isConfirmed()) {
            $this->outputLine('The key is enrolled and trusted by NEOSidekick - no further action needed.');

            return;
        }

        $this->outputLine('<comment>NEOSidekick recorded this key as "%s", so this installation cannot sign with it.</comment>', [(string)$result->status]);
        $this->outputLine('Regenerate the key: <b>./flow agentkey:generate --force</b> or the "Regenerate key" button in the NEOSidekick module.');
    }

    private function outputKeyDetails(): void
    {
        [$keyId, $fingerprint] = $this->readKeyDetailsOrQuit();
        $this->outputLine('Key id (kid):  %s', [$keyId]);
        $this->outputLine('Fingerprint:   %s', [$fingerprint]);
    }
}
