### Update Node Property
@TOKEN=asdf
@NODE_CONTEXT_PATH=/sites/neosdemo/teaser/node52697bdfee199@live
@PROPERTY_NAME=title
POST https://demoaiassistant.ddev.site/neosidekick/aiassistant/api/updateNodeProperty?nodeContextPath={{NODE_CONTEXT_PATH}}&propertyName={{PROPERTY_NAME}}&token={{TOKEN}}
Content-Type: application/json

{
  "status": "success",
  "data": {
    "message": {
      "message": "<h1>Create 💙 testable content.</h1>"
    }
  }
}
