Neos:
  Neos:
    fusion:
      autoInclude:
        NEOSidekick.AiAssistant: true
    userInterface:
      translation:
        autoInclude:
          NEOSidekick.AiAssistant:
            - 'Main'
            - 'Error'
            - 'AssetModule'
    Ui:
      resources:
        javascript:
          'NEOSidekick.AiAssistant':
            resource: resource://NEOSidekick.AiAssistant/Public/NeosUserInterface/Plugin.js
        stylesheets:
          'NEOSidekick.AiAssistant':
            resource: resource://NEOSidekick.AiAssistant/Public/NeosUserInterface/Plugin.css
      configurationDefaultEelContext:
        NEOSidekick.AiAssistant: NEOSidekick\AiAssistant\EelHelper
      frontendConfiguration:
        NEOSidekick.AiAssistant:
          enabled: '${NEOSidekick.AiAssistant.isEnabled()}'
          apiDomain: '${NEOSidekick.AiAssistant.apiDomain()}'
          apiKey: '${NEOSidekick.AiAssistant.apiKey()}'
          userId: '${NEOSidekick.AiAssistant.userId(user)}'
          siteName: '${NEOSidekick.AiAssistant.siteName()}'
          domain: '${NEOSidekick.AiAssistant.domain()}'
          referrer: '${NEOSidekick.AiAssistant.referrer()}'
          defaultLanguage: '${NEOSidekick.AiAssistant.defaultLanguage()}'
          altTextGeneratorModule: '${NEOSidekick.AiAssistant.altTextGeneratorModuleConfiguration()}'
          userInterfaceLanguage: '${q(user).property(''preferences.interfaceLanguage'') || Configuration.setting(''Neos.Neos.userInterface.defaultLanguage'')}'
    modules:
      management:
        submodules:
          neosidekickAiassistantAssets:
            label: 'NEOSidekick.AiAssistant:AssetModule:label'
            icon: 'fas fa-magic'
            controller: 'NEOSidekick\AiAssistant\Controller\AssetModuleController'
            privilegeTarget: 'NEOSidekick.AiAssistant:CanUse'
            mainStylesheet: Lite
            additionalResources:
              javaScripts:
                module: resource://NEOSidekick.AiAssistant/Public/BackendModule/BackendModule.js
  Flow:
    mvc:
      routes:
        'NEOSidekick.AiAssistant': true

NEOSidekick:
  AiAssistant:
    apikey: ''
    developmentBuild: false
    defaultLanguage: 'en'
    altTextGeneratorModule:
      # Defines whether only asset that are used in content should be processed
      # Allowed: true, false, null
      onlyAssetsInUse: null
      # The AssetInterface property to write the generated value to
      # Allowed: title, caption, null
      propertyName: null
      # Predefines how many images should be processed per page, to avoid overload
      # Allowed: 5, 10, 15, 20, 25, null
      limit: 10
      # See allowed language keys in README
      language: null
