Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'NEOSidekick.AiAssistant':
            resource: resource://NEOSidekick.AiAssistant/Public/NeosUserInterface/Plugin.js
        stylesheets:
          'NEOSidekick.AiAssistant':
            resource: resource://NEOSidekick.AiAssistant/Public/NeosUserInterface/Plugin.css
      frontendConfiguration:
        NEOSidekick:
          AiAssistant:
            apikey: ''
