NEOSidekick:
  AiAssistant:
    apikey: ''
    developmentBuild: false
    defaultLanguage: 'en'
    chatSidebarEnabled: true
    modifyTextModal:
      # If set to true, the custom prompt will be focused when the modal opens
      preferCustomPrompt: false
    altTextGeneratorModule:
      # Defines whether only asset that are used in content should be processed, null let's the user choose
      # Allowed: true, false, null
      onlyAssetsInUse: null
      # The AssetInterface property to write the generated value to, null let's the user choose
      # Allowed: title, caption, null
      propertyName: null
      # Predefines how many images should be processed per page, to avoid generate too many in parallel
      # Allowed: 5, 10, 15, 20, 25
      limit: 10
      # The language to write the text in, see allowed language keys in README
      language: null
    focusKeywordGeneratorModule:
      # The workspace name where the nodes are taken from and saved to
      # Allowed: null, live, ... (any other workspace name)
      workspace: null
      # The mode how nodes should be filtered based on the focusKeyword property
      # Allowed:
      #  - only-empty: Only nodes with an empty focusKeyword property are shown
      #  - only-existing: Only nodes with a non-empty focusKeyword property are shown
      #  - both: Both nodes with an empty and  non-empty focusKeyword property are shown
      mode: null
      # Defines whether to automatically start the AI generation of empty focusKeyword property values
      # Allows: null, true, false
      generateEmptyFocusKeywords: null
      # Defines whether to automatically start the AI re-generation of non-empty focusKeyword property values
      # Allows: null, true, false
      regenerateExistingFocusKeywords: null
      # Restrict the node selection to a specific document node type
      # BEWARE: the node type needs to inherit from NEOSidekick.AiAssistant:Mixin.AiPageBriefing
      nodeTypeFilter: null
      # Predefines how many images should be processed per page, to avoid generate too many in parallel
      # Allowed: 5, 10, 15, 20, 25
      limit: 10
