Neos:
  Neos:
    fusion:
      autoInclude:
        NEOSidekick.AiAssistant: true
    userInterface:
      translation:
        autoInclude:
          NEOSidekick.AiAssistant:
            - 'Main'
            - 'Error'
            - 'AiModal'
            - 'Module'
            - 'AssetModule'
            - 'FocusKeywordModule'
            - 'Editors/*'
    Ui:
      resources:
        javascript:
          'NEOSidekick.AiAssistant':
            resource: resource://NEOSidekick.AiAssistant/Public/NeosUserInterface/Plugin.js
        stylesheets:
          'NEOSidekick.AiAssistant':
            resource: resource://NEOSidekick.AiAssistant/Public/NeosUserInterface/Plugin.css
      configurationDefaultEelContext:
        NEOSidekick.AiAssistant: NEOSidekick\AiAssistant\EelHelper
      frontendConfiguration:
        NEOSidekick.AiAssistant:
          enabled: '${NEOSidekick.AiAssistant.isEnabled()}'
          apiDomain: '${NEOSidekick.AiAssistant.apiDomain()}'
          apiKey: '${NEOSidekick.AiAssistant.apiKey()}'
          userId: '${NEOSidekick.AiAssistant.userId(user)}'
          siteName: '${NEOSidekick.AiAssistant.siteName()}'
          domain: '${NEOSidekick.AiAssistant.domain()}'
          referrer: '${NEOSidekick.AiAssistant.referrer()}'
          defaultLanguage: '${NEOSidekick.AiAssistant.defaultLanguage()}'
          chatSidebarEnabled: '${NEOSidekick.AiAssistant.chatSidebarEnabled()}'
          modifyTextModalPreferCustomPrompt: '${NEOSidekick.AiAssistant.modifyTextModalPreferCustomPrompt()}'
          altTextGeneratorModule: '${NEOSidekick.AiAssistant.altTextGeneratorModuleConfiguration()}'
          userInterfaceLanguage: '${q(user).property(''preferences.interfaceLanguage'') || Configuration.setting(''Neos.Neos.userInterface.defaultLanguage'')}'
    modules:
      ai-assistant:
        label: 'NEOSidekick.AiAssistant:Module:label'
        controller: 'NEOSidekick\AiAssistant\Controller\OverviewModuleController'
        description: 'NEOSidekick.AiAssistant:Module:description'
        icon: fas fa-magic
        mainStylesheet: 'Lite'
        privilegeTarget: 'NEOSidekick.AiAssistant:CanUse'
        submodules:
          alternate-text-generator:
            label: 'NEOSidekick.AiAssistant:AssetModule:label'
            description: 'NEOSidekick.AiAssistant:AssetModule:description'
            icon: 'fas fa-images'
            controller: 'NEOSidekick\AiAssistant\Controller\AssetModuleController'
            privilegeTarget: 'NEOSidekick.AiAssistant:CanUse'
            mainStylesheet: Lite
            additionalResources:
              javaScripts:
                module: resource://NEOSidekick.AiAssistant/Public/BackendModule/BackendModule.js
          focus-keyword-generator:
            label: 'NEOSidekick.AiAssistant:FocusKeywordModule:label'
            description: 'NEOSidekick.AiAssistant:FocusKeywordModule:description'
            icon: 'fas fa-search'
            controller: 'NEOSidekick\AiAssistant\Controller\FocusKeywordModuleController'
            privilegeTarget: 'NEOSidekick.AiAssistant:CanUse'
            mainStylesheet: Lite
            additionalResources:
              javaScripts:
                module: resource://NEOSidekick.AiAssistant/Public/BackendModule/BackendModule.js
  Flow:
    mvc:
      routes:
        'NEOSidekick.AiAssistant': true
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'NEOSidekick.AiAssistant:BackendControllers':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'NEOSidekick\AiAssistant\Controller\.*'
