Neos:
  Neos:
    fusion:
      autoInclude:
        NEOSidekick.AiAssistant: true
    userInterface:
      translation:
        autoInclude:
          NEOSidekick.AiAssistant:
            - 'Main'
            - 'Error'
    Ui:
      resources:
        javascript:
          'NEOSidekick.AiAssistant':
            resource: resource://NEOSidekick.AiAssistant/Public/NeosUserInterface/Plugin.js
        stylesheets:
          'NEOSidekick.AiAssistant':
            resource: resource://NEOSidekick.AiAssistant/Public/NeosUserInterface/Plugin.css
      configurationDefaultEelContext:
        NEOSidekick.AiAssistant: NEOSidekick\AiAssistant\EelHelper
      frontendConfiguration:
        NEOSidekick.AiAssistant:
          enabled: '${NEOSidekick.AiAssistant.isEnabled()}'
          apiDomain: '${NEOSidekick.AiAssistant.apiDomain()}'
          apiKey: '${NEOSidekick.AiAssistant.apiKey()}'
          userId: '${NEOSidekick.AiAssistant.userId(user)}'
          siteName: '${NEOSidekick.AiAssistant.siteName()}'
          domain: '${NEOSidekick.AiAssistant.domain()}'
          referrer: '${NEOSidekick.AiAssistant.referrer()}'

NEOSidekick:
  AiAssistant:
    apikey: ''
    developmentBuild: false
