Neos:
  Fusion:
    defaultContext:
      'NEOSidekick': 'NEOSidekick\AiAssistant\EelHelper\NEOSidekickHelper'
      'NEOSidekickInternal': 'NEOSidekick\AiAssistant\EelHelper\NEOSidekickInternalHelper'
  Neos:
    fusion:
      autoInclude:
        NEOSidekick.AiAssistant: true
    userInterface:
      translation:
        autoInclude:
          NEOSidekick.AiAssistant:
            - 'BackendModule/*'
            - 'Editors/*'
            - 'AiModal'
            - 'Error'
            - 'Main'
            - 'Module'
            - 'Editors/*'
            - 'NodeTypes/*'
    Ui:
      resources:
        javascript:
          'NEOSidekick.AiAssistant':
            resource: resource://NEOSidekick.AiAssistant/Public/NeosUserInterface/Plugin.js
        stylesheets:
          'NEOSidekick.AiAssistant':
            resource: resource://NEOSidekick.AiAssistant/Public/NeosUserInterface/Plugin.css
      configurationDefaultEelContext:
        NEOSidekick: NEOSidekick\AiAssistant\EelHelper\NEOSidekickHelper
      frontendConfiguration:
        NEOSidekick.AiAssistant:
          enabled: '${NEOSidekickInternal.isEnabled()}'
          apiDomain: '${NEOSidekickInternal.apiDomain()}'
          apiKey: '${NEOSidekickInternal.apiKey()}'
          userId: '${NEOSidekickInternal.userId(user)}'
          siteName: '${NEOSidekickInternal.siteName()}'
          domain: '${NEOSidekickInternal.domain()}'
          referrer: '${NEOSidekickInternal.referrer()}'
          defaultLanguage: '${NEOSidekickInternal.defaultLanguage()}'
          chatSidebarEnabled: '${NEOSidekickInternal.chatSidebarEnabled()}'
          modifyTextModalPreferCustomPrompt: '${NEOSidekickInternal.modifyTextModalPreferCustomPrompt()}'
          userInterfaceLanguage: '${q(user).property(''preferences.interfaceLanguage'') || Configuration.setting(''Neos.Neos.userInterface.defaultLanguage'')}'
          contentDimensions: '${Neos.Ui.ContentDimensions.contentDimensionsByName()}'
    modules:
      ai-assistant:
        label: 'NEOSidekick.AiAssistant:Module:label'
        controller: 'NEOSidekick\AiAssistant\Controller\BackendModule\OverviewController'
        description: 'NEOSidekick.AiAssistant:Module:description'
        icon: fas fa-magic
        mainStylesheet: 'Lite'
        privilegeTarget: 'NEOSidekick.AiAssistant:CanUse'
        submodules:
          alternate-description-generator:
            label: 'NEOSidekick.AiAssistant:BackendModule.ImageAlternativeText:label'
            description: 'NEOSidekick.AiAssistant:BackendModule.ImageAlternativeText:description'
            icon: 'fas fa-camera'
            controller: 'NEOSidekick\AiAssistant\Controller\BackendModule\ImageAlternativeTextController'
            privilegeTarget: 'NEOSidekick.AiAssistant:CanUse'
            mainStylesheet: Lite
            additionalResources:
              javaScripts:
                module: resource://NEOSidekick.AiAssistant/Public/BackendModule/BackendModule.js
          focus-keyword-generator:
            label: 'NEOSidekick.AiAssistant:BackendModule.FocusKeyword:label'
            description: 'NEOSidekick.AiAssistant:BackendModule.FocusKeyword:description'
            icon: 'fas fa-search'
            controller: 'NEOSidekick\AiAssistant\Controller\BackendModule\FocusKeywordController'
            privilegeTarget: 'NEOSidekick.AiAssistant:CanUse'
            mainStylesheet: Lite
            additionalResources:
              javaScripts:
                module: resource://NEOSidekick.AiAssistant/Public/BackendModule/BackendModule.js
          seo-title-and-meta-description-generator:
            label: 'NEOSidekick.AiAssistant:BackendModule.SeoTitleAndMetaDescription:label'
            description: 'NEOSidekick.AiAssistant:BackendModule.SeoTitleAndMetaDescription:description'
            icon: 'fas fa-tachometer-alt'
            controller: 'NEOSidekick\AiAssistant\Controller\BackendModule\SeoTitleAndMetaDescriptionController'
            privilegeTarget: 'NEOSidekick.AiAssistant:CanUse'
            mainStylesheet: Lite
            additionalResources:
              javaScripts:
                module: resource://NEOSidekick.AiAssistant/Public/BackendModule/BackendModule.js
          seo-image-alt-text-generator:
            label: 'NEOSidekick.AiAssistant:BackendModule.SeoImageAlternativeText:label'
            description: 'NEOSidekick.AiAssistant:BackendModule.SeoImageAlternativeText:description'
            icon: 'fas fa-images'
            controller: 'NEOSidekick\AiAssistant\Controller\BackendModule\SeoImageAlternativeTextController'
            privilegeTarget: 'NEOSidekick.AiAssistant:CanUse'
            mainStylesheet: Lite
            additionalResources:
              javaScripts:
                module: resource://NEOSidekick.AiAssistant/Public/BackendModule/BackendModule.js
          configuration:
            label: 'NEOSidekick.AiAssistant:BackendModule.Configuration:label'
            description: 'NEOSidekick.AiAssistant:BackendModule.Configuration:description'
            icon: 'fas fa-cog'
            controller: 'NEOSidekick\AiAssistant\Controller\BackendModule\ConfigurationController'
            privilegeTarget: 'NEOSidekick.AiAssistant:CanUse'
            mainStylesheet: Lite
  Flow:
    mvc:
      routes:
        'NEOSidekick.AiAssistant': true
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'NEOSidekick.AiAssistant:BackendControllers':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'NEOSidekick\AiAssistant\Controller\.*'
