NEOSidekick:
  AiAssistant:
    apikey: ''
    developmentBuild: false
    defaultLanguage: 'en'
    chatSidebarEnabled: true
    altTextGeneratorModule:
      # Defines whether only asset that are used in content should be processed, null let's the user choose
      # Allowed: true, false, null
      onlyAssetsInUse: null
      # The AssetInterface property to write the generated value to, null let's the user choose
      # Allowed: title, caption, null
      propertyName: null
      # Predefines how many images should be processed per page, to avoid generate too many in parallel
      # Allowed: 5, 10, 15, 20, 25
      limit: 10
      # The language to write the text in, see allowed language keys in README
      language: null
