Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'CodeQ.AiSidekick':
            resource: resource://CodeQ.AiSidekick/Public/NeosUserInterface/Plugin.js
        stylesheets:
          'CodeQ.AiSidekick':
            resource: resource://CodeQ.AiSidekick/Public/NeosUserInterface/Plugin.css
