Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'CodeQ.AdvancedPublish':
            # resource: resource://CodeQ.WritingAssistant/Public/NeosUserInterface/Plugin.js
      frontendConfiguration:
        'CodeQ.WritingAssistant':
          iframeUri: '/neos/management/publications?moduleArguments%5B%40package%5D=codeq.advancedpublish&moduleArguments%5B%40controller%5D=publicationbackendmodule&moduleArguments%5B%40action%5D=new&moduleArguments%5B%40format%5D=html&moduleArguments%5B%40subpackage%5D='

    modules:
      management:
        submodules:
          publications:
            label: 'Chat'
            controller: 'CodeQ\WritingAssistant\Controller\AssistantBackendModuleController'
            description: 'i18n'
            icon: 'icon-star'
            mainStylesheet: 'Lite'
