Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'NEOSidekick.AiAssistant':
            resource: resource://NEOSidekick.AiAssistant/Public/NeosUserInterface/Plugin.js
        stylesheets:
          'NEOSidekick.AiAssistant':
            resource: resource://NEOSidekick.AiAssistant/Public/NeosUserInterface/Plugin.css
  Flow:
    mvc:
      routes:
        'NEOSidekick.AiAssistant':
          position: 'start'
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'NEOSidekick.AiAssistant':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'NEOSidekick\AiAssistant\Controller\.*'

NEOSidekick:
  AiAssistant:
    apikey: ''
